apiVersion: v1
kind: Secret
metadata:
  name: ticketrush-secret
  namespace: ticketrush
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: "CHANGE_ME_USERNAME"
  SPRING_DATASOURCE_PASSWORD: "CHANGE_ME_PASSWORD"
