brokerClusterName = DefaultCluster
brokerName = broker-a
brokerId = 0
storePathRootDir = /home/rocketmq/store
storePathCommitLog = /home/rocketmq/store/commitlog
autoCreateTopicEnable = true
autoCreateSubscriptionGroup = true
